advisor_task:
  description: >
    Conduct a thorough research on global financial markets.
    Make sure you find any interesting and relevant information up to date.
    Based on date from {from_date} to {to_date}.
  expected_output: >
    A list with 10 securities most likely to generate profit with reasoning
    according to its latest performance.
  agent: financial_advisor
  output_file: output/financial_info.md

director_task:
  description: >
    Review the list of securities provided to you.
    Make sure the reasoning is logical and accurate.
    Based on date from {from_date} to {to_date}.
  expected_output: >
    A fully fledged report with the list of securities to buy, sell or stand.
    Providing you wise opinion on the action to take for each of them.
  agent: finance_director
  output_file: output/financial_advise.md
