advisor_task:
  description: >
    Conduct a thorough research on global financial markets.
    Make sure you find any interesting and relevant information up to date.
    Choose only the best securities to invest in.
    Limit search for date from "{from_date}" to "{to_date}".
  expected_output: >
    A list with 10 securities most likely to generate profit with reasoning
    according to its latest performance.
  agent: financial_advisor

director_task:
  description: >
    Review the list of securities provided to you.
    Make sure the reasoning is logical and accurate.
    Remember that information date from "{from_date}" to "{to_date}".
  expected_output: >
    A fully fledged report with the list of securities to buy, sell or hold.
    Providing you wise opinion on the action to take for each of them.
  agent: finance_director
  context: 
  - advisor_task

report_task:
  description: >
    Write the final report with the information provided.
    Report must be dated from "{from_date}" to "{to_date}".
  expected_output: >
    A professional, human readable report.
    Markdown format is to be used.
  agent: report_writer
  context:
  - advisor_task
  - director_task    
  output_file: output\financial_report.md  