[project]
name = "chess-app"
version = "0.1.0"
description = "Chess app with AI agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "flask[async]>=3.1.2",
    "openai-agents>=0.3.0",
    "python-dotenv>=1.1.1",
    "sendgrid>=6.12.4",
]
